package confluence

import (
	"encoding/json"
	"flag"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/KrzysztofBogdan/gitfs/internal/creds"
)

var update = flag.Bool("update", false, "rewrite generated files under docs/confluence")

const docsDir = "../../../docs/confluence"

func TestCanonicalFragment(t *testing.T) {
	a, err := canonicalFragment(`<ac:structured-macro ac:name="info" ac:schema-version="1" ac:macro-id="x1"><ac:rich-text-body><p>i</p></ac:rich-text-body></ac:structured-macro>`)
	if err != nil {
		t.Fatal(err)
	}
	b, _ := canonicalFragment(`<ac:structured-macro ac:schema-version="1" ac:name="info"><ac:rich-text-body><p>i</p></ac:rich-text-body></ac:structured-macro>`)
	if a != b || strings.Contains(a, "macro-id") {
		t.Fatalf("not canonical:\n%s\n%s", a, b)
	}
	p1, _ := canonicalFragment(`<ac:structured-macro ac:name="status"><ac:parameter ac:name="title">T</ac:parameter><ac:parameter ac:name="colour">Red</ac:parameter></ac:structured-macro><ac:link><ri:page ri:content-title="H" ri:version-at-save="3"/></ac:link>`)
	p2, _ := canonicalFragment(`<ac:structured-macro ac:name="status"><ac:parameter ac:name="colour">Red</ac:parameter><ac:parameter ac:name="title">T</ac:parameter></ac:structured-macro><ac:link><ri:page ri:content-title="H"/></ac:link>`)
	if p1 != p2 {
		t.Fatalf("parameter order and version-at-save must not matter:\n%s\n%s", p1, p2)
	}
	if c, _ := canonicalFragment(`<p>a <strong>b</strong></p>`); c == a {
		t.Fatal("different fragments compare equal")
	}
}

func TestSplitMarkers(t *testing.T) {
	ex := []Example{{Variant: "one", Body: "<p>1</p>"}, {Variant: "two", Body: "<p>2</p><hr/>"}}
	got, err := splitMarkers(markerPage(ex))
	if err != nil {
		t.Fatal(err)
	}
	if got["one"] != "<p>1</p>" || got["two"] != "<p>2</p><hr/>" || len(got) != 2 {
		t.Fatalf("%q", got)
	}
}

func readStatus(t *testing.T) map[string]string {
	t.Helper()
	status := map[string]string{}
	b, err := os.ReadFile(filepath.Join(docsDir, "roundtrip.json"))
	if os.IsNotExist(err) {
		return status
	}
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(b, &status); err != nil {
		t.Fatal(err)
	}
	return status
}

func loadDocs(t *testing.T) (ex, rejected []Example) {
	t.Helper()
	fsys := os.DirFS(filepath.Join(docsDir, "examples"))
	ex, err := LoadExamples(fsys)
	if err != nil {
		t.Fatal(err)
	}
	if rejected, err = LoadRejected(fsys); err != nil {
		t.Fatal(err)
	}
	return ex, rejected
}

// TestStorageCatalogue keeps docs/confluence/storage.md in sync with the examples.
func TestStorageCatalogue(t *testing.T) {
	ex, rejected := loadDocs(t)
	if len(ex) == 0 {
		t.Fatal("no examples found")
	}
	got := RenderCatalogue(ex, rejected, readStatus(t))
	path := filepath.Join(docsDir, "storage.md")
	if *update {
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, _ := os.ReadFile(path)
	if string(want) != got {
		t.Fatal("docs/confluence/storage.md is stale: go test ./internal/adapter/confluence -run TestStorageCatalogue -update")
	}
}

// TestStorageExamples pushes every example to a scratch space and records
// what Confluence stores (storage reference spec §2.1). WARNING: creates and
// updates pages under "gfs storage examples" in that space.
//
//	GFS_EXAMPLES_URL=confluence://<host>/<SPACE> go test ./internal/adapter/confluence -run TestStorageExamples -v [-update]
func TestStorageExamples(t *testing.T) {
	raw := os.Getenv("GFS_EXAMPLES_URL")
	if raw == "" {
		t.Skip("set GFS_EXAMPLES_URL to a scratch space to run the live round trip")
	}
	u, err := url.Parse(raw)
	if err != nil {
		t.Fatal(err)
	}
	tg, err := parseTarget(u, nil, os.Getenv, creds.System{})
	if err != nil {
		t.Fatal(err)
	}
	c := newClient(tg)
	var spaces struct {
		Results []struct {
			ID         string `json:"id"`
			HomepageID string `json:"homepageId"`
		} `json:"results"`
	}
	if err := c.do(bg, http.MethodGet, "/wiki/api/v2/spaces?keys="+url.QueryEscape(tg.space), nil, &spaces); err != nil || len(spaces.Results) == 0 {
		t.Fatalf("space %s: %v", tg.space, err)
	}
	space := spaces.Results[0]
	parent := ensurePage(t, c, space.ID, space.HomepageID, "gfs storage examples",
		"<p>Generated by gfs TestStorageExamples: one page per storage node, variants separated by gfs: markers.</p>")

	ex, rejected := loadDocs(t)
	old := readStatus(t)
	status := map[string]string{}
	remote := map[string]string{}
	for _, node := range Nodes(ex) {
		var vs []Example
		for _, e := range ex {
			if e.Node == node {
				vs = append(vs, e)
			}
		}
		id := ensurePage(t, c, space.ID, parent, "gfs example: "+node, markerPage(vs))
		var p apiPage
		if err := c.do(bg, http.MethodGet, "/wiki/api/v2/pages/"+id+"?body-format=storage", nil, &p); err != nil {
			t.Fatalf("%s: fetch: %v", node, err)
		}
		segs, err := splitMarkers(p.Body.Storage.Value)
		if err != nil {
			t.Fatalf("%s: %v", node, err)
		}
		for _, e := range vs {
			want, err := canonicalFragment(e.Body)
			if err != nil {
				t.Fatalf("%s: %v", e.Key(), err)
			}
			got, ok := segs[e.Variant]
			have, _ := canonicalFragment(got)
			if ok && have == want {
				status[e.Key()] = "same"
				continue
			}
			status[e.Key()] = "changed"
			remote[e.Key()] = got
			t.Logf("%s changed\n--- we write\n%s\n--- confluence stores\n%s", e.Key(), want, have)
			if old[e.Key()] == "same" && !*update {
				t.Errorf("%s: regression, was same", e.Key())
			}
		}
	}
	same := 0
	for _, s := range status {
		if s == "same" {
			same++
		}
	}
	t.Logf("%d of %d variants stored unchanged", same, len(status))
	if !*update {
		return
	}
	b, _ := json.MarshalIndent(status, "", "  ")
	if err := os.WriteFile(filepath.Join(docsDir, "roundtrip.json"), append(b, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	for _, e := range ex {
		p := filepath.Join(docsDir, "examples", e.Node, e.Variant+".remote.xml")
		if r, ok := remote[e.Key()]; ok {
			os.WriteFile(p, []byte(r+"\n"), 0o644)
		} else {
			os.Remove(p)
		}
	}
	ex, _ = loadDocs(t)
	if err := os.WriteFile(filepath.Join(docsDir, "storage.md"), []byte(RenderCatalogue(ex, rejected, status)), 0o644); err != nil {
		t.Fatal(err)
	}
}

// ensurePage creates the page or replaces its body, and returns its id.
func ensurePage(t *testing.T, c *client, spaceID, parentID, title, storage string) string {
	t.Helper()
	var found struct {
		Results []apiPage `json:"results"`
	}
	q := "/wiki/api/v2/pages?space-id=" + spaceID + "&title=" + url.QueryEscape(title)
	if err := c.do(bg, http.MethodGet, q, nil, &found); err != nil {
		t.Fatalf("find %q: %v", title, err)
	}
	if len(found.Results) > 0 {
		p := found.Results[0]
		body := map[string]any{"id": p.ID, "status": "current", "title": title, "body": storageBody(storage),
			"version": map[string]any{"number": p.Version.Number + 1, "message": "gfs TestStorageExamples"}}
		if err := c.do(bg, http.MethodPut, "/wiki/api/v2/pages/"+p.ID, body, nil); err != nil {
			t.Fatalf("update %q (v%s): %v", title, strconv.Itoa(p.Version.Number), err)
		}
		return p.ID
	}
	var p apiPage
	body := map[string]any{"spaceId": spaceID, "status": "current", "title": title, "parentId": parentID, "body": storageBody(storage)}
	if err := c.do(bg, http.MethodPost, "/wiki/api/v2/pages", body, &p); err != nil {
		t.Fatalf("create %q: %v", title, err)
	}
	return p.ID
}
