package confluence

import (
	"fmt"
	"sort"
	"strings"
)

// structural elements are checked through macros and adf, not as plain elements.
var structural = map[string]bool{"ac:structured-macro": true, "ac:parameter": true, "ac:adf-node": true, "ac:adf-attribute": true}

// RelaxNG renders a grammar for a whole gfs page file from the vocabulary
// (storage reference spec §3.3): element content is loose, names are strict.
func (v *Vocabulary) RelaxNG() string {
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }
	ignored := make([]string, 0, len(ignoredAttrs))
	for a := range ignoredAttrs {
		ignored = append(ignored, a)
	}
	sort.Strings(ignored)
	attrs := func(ind string, names []string, skip string) {
		for _, a := range names {
			if a != skip {
				w(`%s<optional><attribute name="%s"/></optional>`, ind, a)
			}
		}
		for _, a := range ignored {
			w(`%s<optional><attribute name="%s"/></optional>`, ind, a)
		}
	}
	w(`<?xml version="1.0" encoding="UTF-8"?>`)
	w(`<!-- Generated by gfs from the verified Confluence storage examples; do not edit. -->`)
	w(`<grammar xmlns="http://relaxng.org/ns/structure/1.0" xmlns:ac="%s" xmlns:ri="%s">`, nsAC, nsRI)
	w(`  <start><choice><ref name="envelope"/><ref name="page"/></choice></start>`)
	w(`  <define name="any"><zeroOrMore><choice><attribute><anyName/></attribute><text/><element><anyName/><ref name="any"/></element></choice></zeroOrMore></define>`)
	w(`  <define name="envelope">
    <element name="gfs">
      <zeroOrMore><attribute><anyName/></attribute></zeroOrMore>
      <interleave>
        <element name="content"><ref name="page"/></element>
        <zeroOrMore><element><choice><name>errors</name><name>conflict</name></choice><ref name="any"/></element></zeroOrMore>
      </interleave>
    </element>
  </define>`)
	w(`  <define name="page">
    <element name="page">
      <optional><attribute name="id"/></optional>
      <optional><attribute name="version"/></optional>
      <optional><attribute name="parent"/></optional>
      <optional><attribute name="created"/></optional>
      <optional><attribute name="updated"/></optional>
      <interleave>
        <optional><element name="title"><text/></element></optional>
        <optional><element name="labels"><zeroOrMore><element name="label"><text/></element></zeroOrMore></element></optional>
        <optional><element name="body"><optional><attribute name="type"/></optional><ref name="flow"/></element></optional>
        <zeroOrMore><element name="comment"><zeroOrMore><attribute><choice><name>id</name><name>author</name><name>created</name><name>version</name></choice></attribute></zeroOrMore><ref name="flow"/></element></zeroOrMore>
        <zeroOrMore><element name="attachment"><zeroOrMore><attribute><anyName/></attribute></zeroOrMore><empty/></element></zeroOrMore>
      </interleave>
    </element>
  </define>`)
	w(`  <define name="flow"><mixed><zeroOrMore><ref name="item"/></zeroOrMore></mixed></define>`)
	elems := make([]string, 0, len(v.Elements))
	for e := range v.Elements {
		if !structural[e] {
			elems = append(elems, e)
		}
	}
	sort.Strings(elems)
	w(`  <define name="item">`)
	w(`    <choice>`)
	for _, e := range elems {
		w(`      <ref name="e.%s"/>`, defName(e))
	}
	if len(v.Macros) > 0 {
		w(`      <ref name="macro"/>`)
	}
	if len(v.ADF) > 0 {
		w(`      <ref name="adf"/>`)
	}
	w(`    </choice>`)
	w(`  </define>`)
	for _, e := range elems {
		w(`  <define name="e.%s">`, defName(e))
		w(`    <element name="%s">`, e)
		attrs("      ", v.Elements[e], "")
		w(`      <ref name="flow"/>`)
		w(`    </element>`)
		w(`  </define>`)
	}
	named := func(define, elem, key, childElem, childKey string, m map[string][]string) {
		names := make([]string, 0, len(m))
		for n := range m {
			names = append(names, n)
		}
		sort.Strings(names)
		w(`  <define name="%s">`, define)
		w(`    <choice>`)
		for _, n := range names {
			w(`      <element name="%s">`, elem)
			w(`        <attribute name="%s"><value>%s</value></attribute>`, key, xmlEsc(n))
			attrs("        ", v.Elements[elem], key)
			w(`        <mixed><zeroOrMore><choice>`)
			w(`          <ref name="item"/>`)
			if len(m[n]) > 0 {
				w(`          <element name="%s">`, childElem)
				w(`            <attribute name="%s"><choice>`, childKey)
				for _, p := range m[n] {
					w(`              <value>%s</value>`, xmlEsc(p))
				}
				w(`            </choice></attribute>`)
				attrs("            ", v.Elements[childElem], childKey)
				w(`            <ref name="flow"/>`)
				w(`          </element>`)
			}
			w(`        </choice></zeroOrMore></mixed>`)
			w(`      </element>`)
		}
		w(`    </choice>`)
		w(`  </define>`)
	}
	if len(v.Macros) > 0 {
		named("macro", "ac:structured-macro", "ac:name", "ac:parameter", "ac:name", v.Macros)
	}
	if len(v.ADF) > 0 {
		named("adf", "ac:adf-node", "type", "ac:adf-attribute", "key", v.ADF)
	}
	w(`</grammar>`)
	return b.String()
}

func xmlEsc(s string) string { return attrEsc.Replace(s) }

// defName turns an element name into a define name (NCName: no colon).
func defName(e string) string { return strings.ReplaceAll(e, ":", ".") }
