version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gfs
    main: ./cmd/gfs
    binary: gfs
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags:
      - -s -w -X github.com/KrzysztofBogdan/gitfs/internal/cli.Version={{.Version}}

archives:
  - formats: [tar.gz]
    name_template: "gfs_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - Readme.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^Merge "
