package dnsx

import (
	"fmt"
	"strings"

	"github.com/KrzysztofBogdan/gitfs/internal/schema"
)

// RelaxNG is a grammar for a DNS adapter's files (gfs schema ovh|cloudns):
// the <gfs> envelope, the zone root and its elements by name, attributes
// free (providers add type-specific ones). children names the nested
// elements an element may hold (dnssec: ds; failover: backup). generated
// names other roots the adapter writes (geodns).
func RelaxNG(s *schema.Schema, provider string, children map[string]string, generated ...string) string {
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }
	anyAttrs := `<zeroOrMore><attribute><anyName/></attribute></zeroOrMore>`
	w(`<?xml version="1.0" encoding="UTF-8"?>`)
	w(`<!-- Generated by gfs from its %s zone schema; do not edit. -->`, provider)
	w(`<grammar xmlns="http://relaxng.org/ns/structure/1.0">`)
	w(`  <start><choice><ref name="envelope"/><ref name="root"/></choice></start>`)
	w(`  <define name="any"><zeroOrMore><choice><attribute><anyName/></attribute><text/><element><anyName/><ref name="any"/></element></choice></zeroOrMore></define>`)
	w(`  <define name="envelope">
    <element name="gfs">
      %s
      <interleave>
        <element name="content"><ref name="root"/></element>
        <zeroOrMore><element><choice><name>errors</name><name>conflict</name></choice><ref name="any"/></element></zeroOrMore>
      </interleave>
    </element>
  </define>`, anyAttrs)
	roots := `<ref name="` + s.Root + `"/>`
	if len(generated) > 0 {
		roots += `<ref name="generated"/>`
		var names []string
		for _, g := range generated {
			names = append(names, "<name>"+g+"</name>")
		}
		w(`  <define name="generated"><element><choice>%s</choice><ref name="any"/></element></define>`, strings.Join(names, ""))
	}
	w(`  <define name="root"><choice>%s</choice></define>`, roots)
	var parts []string
	for _, e := range s.Elems {
		inner := "<text/>"
		if c, ok := children[e.Name]; ok {
			inner = fmt.Sprintf(`<mixed><zeroOrMore><element name="%s">%s<text/></element></zeroOrMore></mixed>`, c, anyAttrs)
		}
		parts = append(parts, fmt.Sprintf(`<zeroOrMore><element name="%s">%s%s</element></zeroOrMore>`, e.Name, anyAttrs, inner))
	}
	w(`  <define name="%s">
    <element name="%s">
      %s
      <interleave>
        %s
      </interleave>
    </element>
  </define>`, s.Root, s.Root, anyAttrs, strings.Join(parts, "\n        "))
	w(`</grammar>`)
	return b.String()
}
