package jira

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"sort"
	"strings"

	"github.com/KrzysztofBogdan/gitfs/internal/adapter"
)

// elemTag is a field's element as gfs actions prints it inside <…>.
func elemTag(id string) string {
	if e, ok := systemElems[id]; ok {
		return e
	}
	return fmt.Sprintf("field id=%q", id)
}

// allowedNames reads a screen field's allowed values: their names or values.
func allowedNames(raw []json.RawMessage) []string {
	var out []string
	for _, r := range raw {
		var v struct {
			Name  string `json:"name"`
			Value string `json:"value"`
		}
		json.Unmarshal(r, &v)
		switch {
		case v.Name != "":
			out = append(out, v.Name)
		case v.Value != "":
			out = append(out, v.Value)
		}
	}
	return out
}

// Available lists the transitions the user can take on the issue now, with
// their screen fields, and what the file's own <status> would resolve to
// (jira spec §8).
func (s *session) Available(ctx context.Context, id string, local *adapter.Resource) (adapter.Advice, error) {
	if id == peopleID || id == workflowsID {
		return adapter.Advice{State: "generated by gfs, read-only"}, nil
	}
	var cur struct {
		Fields struct {
			Status struct {
				Name string `json:"name"`
			} `json:"status"`
		} `json:"fields"`
	}
	if err := s.c.Do(ctx, http.MethodGet, "/rest/api/3/issue/"+url.PathEscape(id)+"?fields=status", nil, &cur); err != nil {
		return adapter.Advice{}, err
	}
	ts, err := s.transitions(ctx, id)
	if err != nil {
		return adapter.Advice{}, err
	}
	status := cur.Fields.Status.Name
	adv := adapter.Advice{State: "status: " + status}
	for _, t := range ts {
		it := adapter.Available{Verb: "transition", Name: t.Name, To: t.To.Name}
		ids := make([]string, 0, len(t.Fields))
		for fid := range t.Fields {
			if fid != "comment" {
				ids = append(ids, fid)
			}
		}
		sort.Slice(ids, func(i, j int) bool { // required first, then by element
			if t.Fields[ids[i]].Required != t.Fields[ids[j]].Required {
				return t.Fields[ids[i]].Required
			}
			return elemTag(ids[i]) < elemTag(ids[j])
		})
		for _, fid := range ids {
			f := t.Fields[fid]
			it.Fields = append(it.Fields, adapter.AvailableField{Element: elemTag(fid), Required: f.Required, Allowed: allowedNames(f.AllowedValues)})
		}
		adv.Items = append(adv.Items, it)
	}
	if local != nil {
		if want := textOf(child(local.Root, "status")); want != "" && !strings.EqualFold(want, status) {
			if tr, err := chooseTransition(ts, want); err != nil {
				adv.Note = err.Error()
			} else {
				adv.Note = fmt.Sprintf("local <status> %s -> %q", want, tr.Name)
			}
		}
	}
	return adv, nil
}
