package jira

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/KrzysztofBogdan/gitfs/internal/adapter"
	"github.com/KrzysztofBogdan/gitfs/internal/adapter/atlassian"
)

func results(acts []adapter.Action) []adapter.Result {
	out := make([]adapter.Result, len(acts))
	for i, a := range acts {
		out[i].Action = a
	}
	return out
}

func failAll(out []adapter.Result, err error) []adapter.Result {
	for i := range out {
		out[i].Err, out[i].Code = err, atlassian.Code(err)
	}
	return out
}

// resourceVerb is the verb of the file's own create or delete action, if any.
func resourceVerb(acts []adapter.Action) (int, string) {
	for i, a := range acts {
		if a.Target == "" && !a.IsAttachment() && (a.Verb == "create" || a.Verb == "delete") {
			return i, a.Verb
		}
	}
	return -1, ""
}

// generated refuses changes to .people.xml and .workflows.xml.
func generated(req adapter.ApplyRequest) error {
	for _, r := range []*adapter.Resource{req.Local, req.Base} {
		if r != nil && (r.ID == peopleID || r.ID == workflowsID) {
			return fmt.Errorf("%s is generated by gfs and read-only; changes to it are never sent", r.Path)
		}
	}
	return nil
}

// Apply runs one file's actions (jira spec §7.2): a create or delete alone,
// else the field edits and transition, then comments, worklogs and links in
// the engine's order, then attachments.
func (s *session) Apply(ctx context.Context, req adapter.ApplyRequest) []adapter.Result {
	out := results(req.Actions)
	if err := generated(req); err != nil {
		return failAll(out, err)
	}
	switch i, verb := resourceVerb(req.Actions); verb {
	case "create":
		return s.create(ctx, req)
	case "delete":
		err := s.deleteIssue(ctx, req.Base.ID)
		out[i].Err, out[i].Code = err, atlassian.Code(err)
		return out
	}
	ic, err := s.issueCtx(ctx, req.Local)
	if err != nil {
		return failAll(out, err)
	}
	plan, err := s.planEdit(ctx, ic, req)
	if err != nil {
		return failAll(out, err)
	}
	s.applyEdit(ctx, ic, plan, out)
	for i, a := range req.Actions {
		if a.Target != "" && !a.IsAttachment() {
			err := s.sub(ctx, ic, req, a)
			out[i].Err, out[i].Code = err, atlassian.Code(err)
		}
	}
	for i, a := range req.Actions {
		if a.IsAttachment() {
			out[i].ID, out[i].Err = s.attachment(ctx, ic.id, req, a)
			out[i].Code = atlassian.Code(out[i].Err)
			if out[i].Err == nil && a.Verb == "create" {
				out[i].Version = "-"
			}
		}
	}
	return out
}

// Check resolves one file's actions without writing: people, options,
// transitions, required fields, visibility and link types (jira spec §7.8).
func (s *session) Check(ctx context.Context, req adapter.ApplyRequest) []adapter.Result {
	out := results(req.Actions)
	if err := generated(req); err != nil {
		return failAll(out, err)
	}
	switch i, verb := resourceVerb(req.Actions); verb {
	case "create":
		out[i].Err = s.checkCreate(ctx, req)
		return out
	case "delete":
		out[i].Err = s.checkDelete(ctx, req.Base.ID)
		return out
	}
	ic, err := s.issueCtx(ctx, req.Local)
	if err != nil {
		return failAll(out, err)
	}
	plan, err := s.planEdit(ctx, ic, req)
	if err != nil {
		return failAll(out, err)
	}
	for i, e := range plan.errs {
		out[i].Err = e
	}
	if plan.tr != nil && plan.errs[plan.status] == nil {
		out[plan.status].Detail = transitionDetail(plan)
	}
	for i, a := range req.Actions {
		if a.Target != "" && !a.IsAttachment() {
			_, out[i].Err = s.planSub(ctx, ic, req, a)
		}
	}
	return out
}

// transitionDetail is how a dry run shows the chosen transition:
// "transition In Progress -> Closed (Resolve this issue) with <resolution>".
func transitionDetail(plan *editPlan) string {
	d := fmt.Sprintf("transition %s -> %s (%s)", plan.from, plan.tr.To.Name, plan.tr.Name)
	var with []string
	for id := range plan.trFields {
		with = append(with, elemName(id))
	}
	sort.Strings(with)
	if len(with) > 0 {
		d += " with " + strings.Join(with, ", ")
	}
	return d
}

// checkCreate is the dry run of a new file: the create request and the
// comments, worklogs and links that would follow it.
func (s *session) checkCreate(ctx context.Context, req adapter.ApplyRequest) error {
	plan, err := s.planCreate(ctx, req)
	if err != nil {
		return err
	}
	ic := &issueCtx{id: "new", key: plan.ic.p.Key + "-new", p: plan.ic.p, t: plan.ic.t, set: plan.ic.set}
	var errs []error
	for _, name := range []string{"comment", "worklog", "link"} {
		for n := 1; nthNew(req.Local.Root, name, "id", n) != nil; n++ {
			if _, err := s.planSub(ctx, ic, req, adapter.Action{Verb: "create", Target: fmt.Sprintf("%s[%d]", name, n)}); err != nil {
				errs = append(errs, err)
			}
		}
	}
	return errors.Join(errs...)
}
