package jira

import (
	"io"
	"strings"
	"testing"

	"github.com/KrzysztofBogdan/gitfs/internal/adapter"
	"github.com/KrzysztofBogdan/gitfs/internal/adapter/jira/jtest"
	"github.com/KrzysztofBogdan/gitfs/internal/xmltree"
)

func writes(srv *jtest.Server) int {
	n := 0
	for _, r := range srv.Requests {
		if !strings.HasPrefix(r, "GET ") && !strings.HasPrefix(r, "POST /rest/api/3/search") {
			n++
		}
	}
	return n
}

// wholeFile is GEN-1 with a new summary and status, a comment, a worklog,
// an unknown option and an attachment, in the engine's action order.
func wholeFile(t *testing.T, s *session, srv *jtest.Server, team string) adapter.ApplyRequest {
	t.Helper()
	req, _ := change(t, s, srv.ID("GEN-1"), func(r *xmltree.Node) {
		setText(r, "summary", "Migrate auth to OIDC")
		setText(r, "status", "Done")
		fieldsByID(r)["customfield_10050"].Children = []*xmltree.Node{textEl("option", team)}
		add(r, adfEl("comment", "done"))
		w := el("worklog")
		w.Children = []*xmltree.Node{textEl("started", "2026-09-29T09:00:00.000+0200"), textEl("spent", "30m")}
		add(r, w)
	})
	req.Actions = []adapter.Action{
		{Verb: "update", Group: "summary"}, {Verb: "update", Group: "status"}, {Verb: "update", Group: "field"},
		{Verb: "create", Target: "comment[1]"}, {Verb: "create", Target: "worklog[1]"},
		{Verb: "create", Target: adapter.NewAttachmentTarget("attachment", "a.txt"), File: "gen/GEN-1 Migrate auth.files/a.txt"},
	}
	req.Open = func(string) (io.ReadCloser, error) { return io.NopCloser(strings.NewReader("a")), nil }
	return req
}

func TestApplyWholeFile(t *testing.T) {
	srv, s := editSite(t)
	out := s.Apply(bg, wholeFile(t, s, srv, "Core"))
	for _, r := range out {
		if r.Err != nil {
			t.Fatalf("%+v: %v", r.Action, r.Err)
		}
	}
	if out[1].Detail != "To Do -> Done (Done)" || out[5].ID == "" || out[5].Version != "-" {
		t.Fatalf("%+v", out)
	}
	is := srv.Issue(srv.ID("GEN-1"))
	if is.Status != "Done" || is.Summary != "Migrate auth to OIDC" || len(is.Comments) != 1 || len(is.Worklogs) != 1 || len(is.Attachments) != 1 {
		t.Fatalf("%+v", is)
	}
}

func TestCheckWritesNothing(t *testing.T) {
	srv, s := editSite(t)
	req := wholeFile(t, s, srv, "Core")
	setText(req.Local.Root, "status", "Shipped")
	add(req.Local.Root, adfEl("comment", "second", "public", "true"))
	req.Actions = append(req.Actions, adapter.Action{Verb: "create", Target: "comment[2]"})
	srv.Requests = nil
	out := s.Check(bg, req)
	if writes(srv) != 0 {
		t.Fatalf("Check wrote: %v", srv.Requests)
	}
	if out[1].Err == nil || !strings.Contains(out[1].Err.Error(), `"Shipped" is not reachable`) || out[0].Err != nil || out[2].Err != nil ||
		out[6].Err == nil || !strings.Contains(out[6].Err.Error(), "GEN is not one") {
		t.Fatalf("%+v", out)
	}
	req = wholeFile(t, s, srv, "Core")
	if out := s.Check(bg, req); out[1].Detail != "transition To Do -> Done (Done)" || out[1].Err != nil {
		t.Fatalf("%+v", out[1])
	}
}

func TestCheckCreateAndDelete(t *testing.T) {
	srv, s := editSite(t)
	srv.Requests = nil
	out := s.Check(bg, newFile(t, "gen/New.xml", `<issue><type>Task</type><summary>N</summary><link type="nope">GEN-1</link></issue>`))
	if out[0].Err == nil || !strings.Contains(out[0].Err.Error(), `unknown link type "nope"`) || writes(srv) != 0 {
		t.Fatalf("%v %v", out[0].Err, srv.Requests)
	}
	base, _ := s.Fetch(bg, srv.ID("GEN-1"))
	out = s.Check(bg, adapter.ApplyRequest{Base: base, Actions: []adapter.Action{{Verb: "delete"}}})
	if out[0].Err == nil || !strings.Contains(out[0].Err.Error(), "sub-tasks first") {
		t.Fatal(out[0].Err)
	}
	out = s.Apply(bg, adapter.ApplyRequest{Base: base, Actions: []adapter.Action{{Verb: "delete"}}})
	if out[0].Err == nil || srv.Issue(srv.ID("GEN-1")) == nil {
		t.Fatal("refused delete must not delete")
	}
}

func TestGeneratedFilesRefused(t *testing.T) {
	_, s := editSite(t)
	p, _ := s.Fetch(bg, peopleID)
	req := adapter.ApplyRequest{Local: p, Base: p, Actions: []adapter.Action{{Verb: "update", Group: "person"}}}
	for _, out := range [][]adapter.Result{s.Check(bg, req), s.Apply(bg, req)} {
		if out[0].Err == nil || out[0].Err.Error() != ".people.xml is generated by gfs and read-only; changes to it are never sent" {
			t.Fatal(out[0].Err)
		}
	}
}

func TestDescribe(t *testing.T) {
	root := parse(t, `<issue><type>Bug</type><status>Closed</status>
  <comment public="true">a</comment><comment internal="true">b</comment><comment>c</comment>
  <worklog><started>s</started><spent>2h</spent></worklog><link type="blocks">GEN-9</link></issue>`)
	local := &adapter.Resource{Path: "gen/New.xml", Root: root}
	cases := []struct {
		a             adapter.Action
		class, detail string
	}{
		{adapter.Action{Verb: "create"}, "create", "create Bug in GEN"},
		{adapter.Action{Verb: "delete"}, "delete", "delete issue"},
		{adapter.Action{Verb: "update", Group: "status"}, "transition", "transition to Closed"},
		{adapter.Action{Verb: "update", Group: "field"}, "update", "update custom fields"},
		{adapter.Action{Verb: "update", Group: "priority"}, "update", "update priority"},
		{adapter.Action{Verb: "create", Target: "comment[1]"}, "reply", "add public reply (emails the customer)"},
		{adapter.Action{Verb: "create", Target: "comment[2]"}, "comment", "add internal comment"},
		{adapter.Action{Verb: "create", Target: "comment[3]"}, "comment", "add comment"},
		{adapter.Action{Verb: "update", Target: "comment[id=5]"}, "comment", "edit comment 5"},
		{adapter.Action{Verb: "delete", Target: "comment[id=5]"}, "delete", "delete comment 5"},
		{adapter.Action{Verb: "create", Target: "worklog[1]"}, "worklog", "log 2h"},
		{adapter.Action{Verb: "create", Target: "link[1]"}, "link", "link: blocks GEN-9"},
		{adapter.Action{Verb: "delete", Target: "link[id=7]"}, "delete", "delete link 7"},
		{adapter.Action{Verb: "create", Target: "attachment[file=a.png]", File: "gen/New.files/a.png"}, "create", "attach a.png"},
	}
	for _, c := range cases {
		a := c.a
		(&Adapter{}).Describe(&a, local)
		if a.Class != c.class || a.Detail != c.detail {
			t.Errorf("%+v: %s %q, want %s %q", c.a, a.Class, a.Detail, c.class, c.detail)
		}
	}
}

func TestAvailable(t *testing.T) {
	srv, now := site(t)
	supportFlow(srv)
	srv.SetFields("SUP", "3",
		jtest.Field{ID: "summary", Name: "Summary", Type: "string", Required: true},
		jtest.Field{ID: "resolution", Name: "Resolution", Type: "resolution",
			Options: []jtest.Option{{ID: "1", Value: "Done"}, {ID: "2", Value: "Won't Do"}}},
		jtest.Field{ID: "customfield_10040", Name: "Users", Type: "string", Custom: typeText})
	s := open(t, srv, now, selection{keys: []string{"SUP"}}, "")
	id := srv.ID("SUP-1")
	local, _ := s.Fetch(bg, id)
	setText(local.Root, "status", "Closed")
	adv, err := s.Available(bg, id, local)
	if err != nil {
		t.Fatal(err)
	}
	if adv.State != "status: In Progress" || len(adv.Items) != 2 || adv.Items[0].Name != "Resolve this issue" {
		t.Fatalf("%+v", adv)
	}
	f := adv.Items[0].Fields
	if len(f) != 2 || f[0].Element != "resolution" || !f[0].Required || strings.Join(f[0].Allowed, "|") != "Done|Won't Do" ||
		f[1].Element != `field id="customfield_10040"` || f[1].Required {
		t.Fatalf("%+v", f)
	}
	if !strings.HasPrefix(adv.Note, `several transitions lead to "Closed"`) {
		t.Fatal(adv.Note)
	}
}
