package jira

import (
	"fmt"
	"sort"
	"strings"
)

// RelaxNG is a grammar for Jira files (gfs schema jira): the <issue> and
// <request> structure, and the ADF vocabulary inside bodies. Element names
// are strict; attributes are free, since ADF attributes are open-ended.
func RelaxNG() string {
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }
	anyAttrs := `<zeroOrMore><attribute><anyName/></attribute></zeroOrMore>`
	text := func(name string) string { return fmt.Sprintf(`<element name="%s">%s<text/></element>`, name, anyAttrs) }
	w(`<?xml version="1.0" encoding="UTF-8"?>`)
	w(`<!-- Generated by gfs from its ADF tables (@atlaskit/adf-schema 57.6); do not edit. -->`)
	w(`<grammar xmlns="http://relaxng.org/ns/structure/1.0">`)
	w(`  <start><choice><ref name="envelope"/><ref name="root"/></choice></start>`)
	w(`  <define name="any"><zeroOrMore><choice><attribute><anyName/></attribute><text/><element><anyName/><ref name="any"/></element></choice></zeroOrMore></define>`)
	w(`  <define name="envelope">
    <element name="gfs">
      %s
      <interleave>
        <element name="content"><ref name="root"/></element>
        <zeroOrMore><element><choice><name>errors</name><name>conflict</name></choice><ref name="any"/></element></zeroOrMore>
      </interleave>
    </element>
  </define>`, anyAttrs)
	w(`  <define name="root"><choice><ref name="issue"/><ref name="request"/><ref name="generated"/></choice></define>`)
	w(`  <define name="generated"><element><choice><name>people</name><name>workflows</name></choice><ref name="any"/></element></define>`)
	w(`  <define name="user"><element><choice><name>user</name><name>assignee</name><name>reporter</name><name>creator</name><name>participant</name></choice>%s<text/></element></define>`, anyAttrs)
	w(`  <define name="field">
    <element name="field">
      %s
      <mixed><zeroOrMore><choice>
        %s %s %s <ref name="user"/> <ref name="block"/> <ref name="inline"/>
      </choice></zeroOrMore></mixed>
    </element>
  </define>`, anyAttrs, text("option"), text("label"), text("sprint"))
	list := func(name, item string) string {
		return fmt.Sprintf(`<optional><element name="%s"><zeroOrMore>%s</zeroOrMore></element></optional>`, name, text(item))
	}
	body := func(name string) string {
		return fmt.Sprintf(`<optional><element name="%s">%s<ref name="adf"/></element></optional>`, name, anyAttrs)
	}
	w(`  <define name="issue">
    <element name="issue">
      %s
      <interleave>`, anyAttrs)
	for _, f := range []string{"summary", "type", "status", "resolution", "priority", "parent", "due"} {
		w(`        <optional>%s</optional>`, text(f))
	}
	w(`        <zeroOrMore><ref name="user"/></zeroOrMore>`)
	w(`        %s`, list("labels", "label"))
	w(`        %s`, list("components", "component"))
	w(`        %s`, list("fixVersions", "version"))
	w(`        %s`, list("affectsVersions", "version"))
	w(`        <optional><element name="timetracking">%s<interleave><optional>%s</optional><optional>%s</optional></interleave></element></optional>`, anyAttrs, text("original"), text("remaining"))
	w(`        <zeroOrMore><ref name="field"/></zeroOrMore>`)
	w(`        %s`, body("environment"))
	w(`        %s`, body("description"))
	w(`        <zeroOrMore>%s</zeroOrMore>`, text("link"))
	w(`        <zeroOrMore><element name="attachment">%s<empty/></element></zeroOrMore>`, anyAttrs)
	w(`        <zeroOrMore><element name="comment">%s<ref name="adf"/></element></zeroOrMore>`, anyAttrs)
	w(`        <zeroOrMore><element name="worklog">%s<interleave><optional>%s</optional><optional>%s</optional>%s</interleave></element></zeroOrMore>`,
		anyAttrs, text("started"), text("spent"), body("comment"))
	w(`      </interleave>
    </element>
  </define>`)
	w(`  <define name="request">
    <element name="request">
      %s
      <interleave>`, anyAttrs)
	for _, f := range []string{"summary", "requestType", "status"} {
		w(`        <optional>%s</optional>`, text(f))
	}
	w(`        <zeroOrMore><ref name="user"/></zeroOrMore>`)
	w(`        <zeroOrMore><ref name="field"/></zeroOrMore>`)
	w(`        <optional>%s</optional>`, text("description"))
	w(`        <zeroOrMore><element name="approval">%s<empty/></element></zeroOrMore>`, anyAttrs)
	w(`        <zeroOrMore><element name="attachment">%s<empty/></element></zeroOrMore>`, anyAttrs)
	w(`        <zeroOrMore>%s</zeroOrMore>`, text("comment"))
	w(`      </interleave>
    </element>
  </define>`)
	nodes := make([]string, 0, len(adfNodes))
	for n := range adfNodes {
		nodes = append(nodes, n)
	}
	sort.Strings(nodes)
	w(`  <define name="adf"><mixed><zeroOrMore><choice><ref name="block"/><ref name="inline"/></choice></zeroOrMore></mixed></define>`)
	w(`  <define name="block"><choice>`)
	for _, n := range nodes {
		w(`    <element name="%s">%s<ref name="adf"/></element>`, n, anyAttrs)
	}
	w(`    <element name="%s"><text/></element>`, adfRaw)
	w(`  </choice></define>`)
	w(`  <define name="inline"><choice>`)
	for _, m := range adfMarks {
		w(`    <element name="%s">%s<ref name="adf"/></element>`, m, anyAttrs)
	}
	w(`    <element name="text"><text/></element>`)
	w(`  </choice></define>`)
	w(`</grammar>`)
	return b.String()
}
